### ISSUE TITLE
the tab button can not be clicked

### ISSUE THREAD

**Issue by hityb** [xplosionmind/firefox-monoline#15]
OS: Windows 10 22H2
Firefox version: 126.0
the tab button can not be clicked（left mouse click and right mouse click）, should you fix it?
![image](https://github.com/xplosionmind/firefox-monoline/assets/58910855/6335de83-a516-4b65-86a2-4d9d3a97ca5d)

**Comment by elias-rod** [comment]
@xplosionmind

**Comment by xplosionmind** [comment]
Sorry for replying only now. I am not maintaining this anymore. See #16.
